version: '3'
services:
  node:
    restart: always
    build: .
    command: /usr/src/app/node_modules/.bin/nodemon ./src/
    environment:
      - mongoo1_twitterBearerToken=${mongoo1_twitterBearerToken}
      - mongoo1_standardFollowerId=${mongoo1_standardFollowerId}
    ports:
      - 3030:3030
    volumes:
      - ./:/code
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb:
